### ISSUE TITLE
Navigation sidebar is light even in dark mode

### ISSUE THREAD

**Issue by posimagi** [posimagi/bg-wiki-dark-mode#10]
This is most likely an issue in `resources/themes/wikimedia.less.orig`. The underlying issue has been taken care of, but there may be additional steps needed to recompile, redistribute, and/or cache-purge the faulty style.

![image](https://user-images.githubusercontent.com/1747598/226522736-5c6f67ae-1b86-4767-9b08-2cd22dfd02b1.png)

**Comment by posimagi** [comment]
Thankfully the changes worked their way through the cache and the issue is resolved.

![image](https://user-images.githubusercontent.com/1747598/226557859-a5f41147-9199-4dcf-8ffc-15a18989b477.png)

**Comment by rijaxo** [comment]
![sidebar](https://user-images.githubusercontent.com/7748508/227668963-3e4169e5-337f-4995-9dcf-b1ba26542484.png)

Still seeing this today

**Comment by posimagi** [comment]
Thanks for the report. I believe this is related to the DynamicSidebar extension, as I've seen some different sidebar issues even after the change a few days ago. I am looking into it.

**Comment by posimagi** [comment]
It's still unclear what's causing this issue. There are a couple more places on the LESS side that may be pulling this style that I need to look into.

**Comment by posimagi** [comment]
So I found something weird. Happened to get dark sidebar in dark mode, and the inspector says it's getting that from `load.php` (this is what I see for the vast majority of styles in general). But on a page with an erroneous light sidebar in dark mode, it's getting the style from the `<style>` tag. That is still going to `load.php` but with a different REST URI.

Light sidebar on dark mode (wrong): 
```
https://www.bg-wiki.com/load.php?lang=en&modules=mediawiki.action.edit.styles%7Cmediawiki.action.styles%7Cmediawiki.editfont.styles%7Cmediawiki.helplink%7Cmediawiki.interface.helpers.styles%7Cmediawiki.widgets.styles%7Coojs-ui-core.icons%2Cstyles%7Coojs-ui.styles.indicators%7Cskins.timelessdark&only=styles&skin=timelessdark
```
Dark sidebar on dark mode (right): 
```
https://www.bg-wiki.com/load.php?lang=en&modules=jquery.makeCollapsible.styles%7Cskins.timelessdark&only=styles&skin=timelessdark
```

You can see that the wrong stylesheet seems to be ORing (`%7C` is the pipe operator `|`) more stuff, and the incorrect style being applied (`background: #f8f9fa`) appears 8 times in the wrong stylesheet versus only 4 times in the right stylesheet.

The four times that the offending style appears in the wrong stylesheet distinct from the right one are:
```
.oo-ui-buttonElement-framed.oo-ui-widget-enabled > .oo-ui-buttonElement-button,
.oo-ui-dropdownInputWidget.oo-ui-widget-enabled,
.oo-ui-textInputWidget.oo-ui-widget-enabled .oo-ui-inputWidget-input[readonly]:not(.oo-ui-pendingElement-pending),
.oo-ui-dropdownWidget.oo-ui-widget-enabled .oo-ui-dropdownWidget-handle
```

This is strange because not only do none of them appear to be related to the element in question (`#mw-site-navigation .sidebar-chunk`), but I can confirm that manually selecting all four and changing their background to red does not affect anything visible on the page.

**Comment by posimagi** [comment]
Removing `oojs-ui.styles.indicators` from the stylesheet `<link>` resulted in correct rendering, but then adding it back did not revert the rendering to being incorrect, so it's possible that incorrect stylesheets are being cached.

**Comment by posimagi** [comment]
Implemented an override in both skins to force the colors, here's hoping it actually works.

**Comment by posimagi** [comment]
This seems to be _mostly_ fixed now. There are still some issues with incorrect borders, but those are less urgent, so I'm closing this ticket unless things become a problem again.
